name: bootloader

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Bootloader
    runs-on: macos-latest 
    steps: 
    - uses: actions/checkout@v2
    - run: brew tap ArmMbed/homebrew-formulae
    - run: brew install arm-none-eabi-gcc 
    - uses: actions-rs/toolchain@v1
      with: 
        toolchain: nightly
        target: thumbv7m-none-eabi
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target thumbv7m-none-eabi
